### ISSUE TITLE
How to install/use this

### ISSUE THREAD

**Issue by sanchari24** [tushiqi/MAnorm2_utils#2]
Hello, I cloned the git repository. I wanted to know how to install this ?

Thanks

**Comment by Kevin-Brockers** [comment]
I think you can easily pip install it.

Link: https://pypi.org/project/MAnorm2-utils/

**Comment by tushiqi** [comment]
@sanchari24 

Sincerely sorry for my late response.
Yes, you can simply type “**pip install MAnorm2-utils**” on command line to install the software. I believe this is the easiest way.
Alternatively, I have put software distributions under the “**dist**” directory. You can make the installation by selecting an appropriate distribution. For example, download “**MAnorm2_utils-1.0.0.tar.gz**” and finish the installation by typing “**pip install /path/to/MAnorm2_utils-1.0.0.tar.gz**”.
